version: "2.17.2"
services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      ELASTIC_PASSWORD: elastic
      KIBANA_PASSWORD: kibana
      discovery.type: single-node
      xpack.security.http.ssl.enabled: false
      xpack.security.authc.anonymous.username: elastic
      xpack.security.authc.anonymous.roles: superuser
      xpack.security.authc.anonymous.authz_exception: true
